### ISSUE TITLE
JS error in preview on initial setup

### ISSUE THREAD

**Issue by JarrydLong** [DLXPlugins/dlx-pmpro-turnstile#3]
I'm getting a JS error when trying to preview from the settings page

![image](https://github.com/DLXPlugins/dlx-pmpro-turnstile/assets/8989542/759207c1-2e79-407e-99c4-12a71975d1be)

Steps to replicate:
1. Clean install using Paid Memberships Pro - Add Cloudflare Turnstile 1.0.1
2. Navigate to Turnstile settings /wp-admin/admin.php?page=dlx-pmpro-turnstile
3. Fill out a test API key
4. Hit the Preview button,  the preview modal shows but not the Cloudflare section
5. Hit the Save settings and tried again - same error

**Comment by ronalfy** [comment]
This was due to a mis-capitalized `widgettheme` variable, causing the issue. It has been resolved in 1.0.2
